package userInterface;

/**
 *
 * @author Kelvin Bonilla
 */
public class GCDFrame extends javax.swing.JFrame
{

    MainMenuFrame mainMenu;
    /**
     * Creates new form GCDFrame
     */
    public GCDFrame(MainMenuFrame mainMenu, Integer firstInt, Integer secondInt) {
        initComponents();
        this.mainMenu = mainMenu;
        Integer gcd = calculateGCD(firstInt.intValue(), secondInt.intValue());
        
        firstIntTxtField.setText(firstInt.toString());
        secondIntTxtField.setText(secondInt.toString());
        gcdTxtField.setText(gcd.toString());
    }

    private int calculateGCD(int firstInt, int secondInt)
    {
        return sourceCode.access.DAO.gcd(firstInt, secondInt);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstIntLbl = new javax.swing.JLabel();
        firstIntTxtField = new javax.swing.JTextField();
        secondIntLbl = new javax.swing.JLabel();
        secondIntTxtField = new javax.swing.JTextField();
        gcdLbl = new javax.swing.JLabel();
        gcdTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Calculate GCD");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingEvt(evt);
            }
        });

        firstIntLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        firstIntLbl.setText("First Integer:");
        firstIntLbl.setToolTipText("Labels the text field on the right");

        firstIntTxtField.setEditable(false);
        firstIntTxtField.setToolTipText("Displays the value of the first integer");

        secondIntLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        secondIntLbl.setText("Second Integer:");
        secondIntLbl.setToolTipText("Labels the text field on the right");

        secondIntTxtField.setEditable(false);
        secondIntTxtField.setToolTipText("Displays the value of the second integer");

        gcdLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        gcdLbl.setText("GCD:");
        gcdLbl.setToolTipText("Greatest Common Divisor; Labels the text field on the right");

        gcdTxtField.setEditable(false);
        gcdTxtField.setToolTipText("Displays the value of the greatest common divisor");

        backBtn.setText("Back");
        backBtn.setToolTipText("");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstIntLbl)
                            .addComponent(secondIntLbl)
                            .addComponent(gcdLbl))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(firstIntTxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(secondIntTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gcdTxtField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstIntLbl)
                    .addComponent(firstIntTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondIntLbl)
                    .addComponent(secondIntTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gcdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gcdLbl))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        TitleFrameApp.displayFrame(mainMenu, this);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void windowClosingEvt(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingEvt
        backBtn.doClick();
    }//GEN-LAST:event_windowClosingEvt

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel firstIntLbl;
    private javax.swing.JTextField firstIntTxtField;
    private javax.swing.JLabel gcdLbl;
    private javax.swing.JTextField gcdTxtField;
    private javax.swing.JLabel secondIntLbl;
    private javax.swing.JTextField secondIntTxtField;
    // End of variables declaration//GEN-END:variables
}
