package userInterface;

/**
 *
 * @author Kelvin Bonilla
 */
public class SearchingSortingQFrame extends javax.swing.JFrame
{

    private final javax.swing.JFrame previousWindow;
    /**
     * Creates new form SearchingSortingQFrame
     */
    public SearchingSortingQFrame(javax.swing.JFrame previousWindow) {
        initComponents();
        this.previousWindow = previousWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrayIntegerTxt = new javax.swing.JTextField();
        searchingBtn = new javax.swing.JButton();
        sortingBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Searching Or Sorting?");
        setResizable(false);

        arrayIntegerTxt.setEditable(false);
        arrayIntegerTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        arrayIntegerTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arrayIntegerTxt.setText("Are you comparing searching algorithms or sorting algorithms?");
        arrayIntegerTxt.setToolTipText("");
        arrayIntegerTxt.setBorder(null);

        searchingBtn.setText("Searching Algorithms");
        searchingBtn.setToolTipText("This button will bring you to the \"Searching Menu\" window.");
        searchingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingBtnActionPerformed(evt);
            }
        });

        sortingBtn.setText("Sorting Algorithms");
        sortingBtn.setToolTipText("This button brings you to the \"Sorting Menu\" window.");
        sortingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.setToolTipText("Closes this window and brings you back to the \"Introduction\" window.");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(arrayIntegerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(searchingBtn)
                .addGap(69, 69, 69)
                .addComponent(sortingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(arrayIntegerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortingBtn)
                    .addComponent(backBtn)
                    .addComponent(searchingBtn))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingBtnActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented yet.", "Implementation error.", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_searchingBtnActionPerformed

    private void sortingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingBtnActionPerformed
        TitleFrameApp.displayFrame(new SortingAlgorithmsMenuFrame(this), this);
        dispose();
    }//GEN-LAST:event_sortingBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        TitleFrameApp.displayFrame(previousWindow, this);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrayIntegerTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton searchingBtn;
    private javax.swing.JButton sortingBtn;
    // End of variables declaration//GEN-END:variables
}
