package userInterface;

/**
 *
 * @author Kelvin Bonilla
 */
public class SortingFrame extends javax.swing.JFrame
{
    private MainMenuFrame mainMenu;
    /**
     * Creates new form SortingFrame
     */
    public SortingFrame(MainMenuFrame mainMenu, String arrayName, String sortType , sourceCode.access.SAHIAccess toSort) {
        initComponents();
        this.mainMenu = mainMenu;
        if(toSort.getCurSortState() == sourceCode.data.SAHIPlus.SortState.SORTED)
            setInfo(arrayName, sortType, toSort.toString());
        else
        {
            if(sortType.equalsIgnoreCase("Bubble Sort"))
                toSort.sort(sourceCode.data.SAHIPlus.SortType.BUBBLE);
            else if(sortType.equalsIgnoreCase("Insertion Sort"))
                toSort.sort(sourceCode.data.SAHIPlus.SortType.INSERTION);
            setInfo(arrayName, sortType, toSort.toString());
        }
        
    }

    private void setInfo(String selectedInfo, String sortTypeInfo, String resultsInfo)
    {
        selectedTxtField.setText(selectedInfo);
        sortTypeTxtField.setText(sortTypeInfo);
        resultsTxtArea.setText(resultsInfo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectedLbl = new javax.swing.JLabel();
        selectedTxtField = new javax.swing.JTextField();
        sortTypeLbl = new javax.swing.JLabel();
        sortTypeTxtField = new javax.swing.JTextField();
        resultsLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTxtArea = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sorting Results");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingEvt(evt);
            }
        });

        selectedLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        selectedLbl.setText("Selected:");
        selectedLbl.setToolTipText("The array to be sorted");

        selectedTxtField.setEditable(false);
        selectedTxtField.setToolTipText("Displaying the name of the array selected previously");

        sortTypeLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sortTypeLbl.setText("Sort Type:");
        sortTypeLbl.setToolTipText("The type of sort to be done on the array");

        sortTypeTxtField.setEditable(false);
        sortTypeTxtField.setToolTipText("Displaying the name of the sort chosen previously");

        resultsLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resultsLbl.setText("Results:");
        resultsLbl.setToolTipText("The results of sorting the data");

        resultsTxtArea.setEditable(false);
        resultsTxtArea.setColumns(20);
        resultsTxtArea.setLineWrap(true);
        resultsTxtArea.setRows(5);
        resultsTxtArea.setToolTipText("Displaying the results of sorting the array");
        resultsTxtArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resultsTxtArea);

        backBtn.setText("Back");
        backBtn.setToolTipText("Closes this window and brings you back to the Main Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedLbl)
                            .addComponent(sortTypeLbl)
                            .addComponent(resultsLbl))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedTxtField)
                            .addComponent(sortTypeTxtField)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedLbl)
                    .addComponent(selectedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortTypeLbl)
                    .addComponent(sortTypeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultsLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        TitleFrameApp.displayFrame(mainMenu, this);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void windowClosingEvt(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingEvt
        backBtn.doClick();
    }//GEN-LAST:event_windowClosingEvt


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultsLbl;
    private javax.swing.JTextArea resultsTxtArea;
    private javax.swing.JLabel selectedLbl;
    private javax.swing.JTextField selectedTxtField;
    private javax.swing.JLabel sortTypeLbl;
    private javax.swing.JTextField sortTypeTxtField;
    // End of variables declaration//GEN-END:variables
}
