package userInterface;

/**
 *
 * @author Kelvin Bonilla
 */
public class StoreArrayFrame extends javax.swing.JFrame
{

    private final MainMenuFrame MAIN_MENU;
    /**
     * Creates new form StoreArrayFrame
     */
    public StoreArrayFrame(MainMenuFrame mainMenu) {
        initComponents();
        MAIN_MENU = mainMenu;
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numElementBtnGroup = new javax.swing.ButtonGroup();
        tenElementsRadioBtn = new javax.swing.JRadioButton();
        hunElementsRadioBtn = new javax.swing.JRadioButton();
        fivHunElementsRadioBtn = new javax.swing.JRadioButton();
        numElementsLbl = new javax.swing.JLabel();
        arrayNameLbl = new javax.swing.JLabel();
        arrayNameTxtField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Store An Array");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingEvt(evt);
            }
        });

        numElementBtnGroup.add(tenElementsRadioBtn);
        tenElementsRadioBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tenElementsRadioBtn.setText("10");
        tenElementsRadioBtn.setToolTipText("Choice of a 10 element array, with numbers ranging from 0 to 10");

        numElementBtnGroup.add(hunElementsRadioBtn);
        hunElementsRadioBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hunElementsRadioBtn.setText("100");
        hunElementsRadioBtn.setToolTipText("Choice of a 100 element array, with numbers ranging from 0 to 100");

        numElementBtnGroup.add(fivHunElementsRadioBtn);
        fivHunElementsRadioBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fivHunElementsRadioBtn.setText("500");
        fivHunElementsRadioBtn.setToolTipText("Choice of a 500 element array, with numbers ranging from 0 to 500");

        numElementsLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numElementsLbl.setText("Number of Elements:");
        numElementsLbl.setToolTipText("This determines the number of elements the array will have, as well as the range of numbers the array will store (from 0 to 10/100/1000)");

        arrayNameLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        arrayNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        arrayNameLbl.setText("Name of The Array:");
        arrayNameLbl.setToolTipText("The name that this array will be associated with in the Main Menu");

        arrayNameTxtField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        arrayNameTxtField.setText("[Enter Name Here]");
        arrayNameTxtField.setToolTipText("The field used to type the name that this array will use");
        arrayNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldFocusGained(evt);
            }
        });
        arrayNameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterKeyPressed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.setToolTipText("Closes this window and brings you back to the \"Array or Integer?\" window");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.setToolTipText("Stores the array into the Main Menu");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arrayNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numElementsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tenElementsRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hunElementsRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fivHunElementsRadioBtn))
                            .addComponent(arrayNameTxtField))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hunElementsRadioBtn)
                    .addComponent(tenElementsRadioBtn)
                    .addComponent(fivHunElementsRadioBtn)
                    .addComponent(numElementsLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrayNameLbl)
                    .addComponent(arrayNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldFocusGained
        if (evt.getComponent() instanceof javax.swing.JTextField)
        {
            javax.swing.JTextField tf = (javax.swing.JTextField) evt.getComponent();
            tf.selectAll();
        }
    }//GEN-LAST:event_txtFieldFocusGained

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        int size;
        
        if(tenElementsRadioBtn.isSelected())
            size = 10;
        else if(hunElementsRadioBtn.isSelected())
            size = 100;
        else if(fivHunElementsRadioBtn.isSelected())
            size = 500;
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Number of elements haven't been chosen!", "Size Choice Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        sourceCode.access.SAHIAccess<Integer> theArray = sourceCode.access.DAO.getCompareableArrayHolder(size);
        String theName = arrayNameTxtField.getText();
        java.util.Random rand = new java.util.Random();
        
        for(int i = 0; i < size; i++)
            theArray.add(rand.nextInt(size + 1));        
        
        MAIN_MENU.addData(theName, theArray);
        
        javax.swing.JOptionPane.showMessageDialog(this, theName + " has been stored.", "Array Submitted", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        arrayNameTxtField.setText("[Enter Name Here]");
        arrayNameTxtField.requestFocusInWindow();
        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        TitleFrameApp.displayFrame(new Array_Integer_Popup(MAIN_MENU), this);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void windowClosingEvt(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingEvt
        TitleFrameApp.displayFrame(new Array_Integer_Popup(MAIN_MENU), this);
        dispose();
    }//GEN-LAST:event_windowClosingEvt

    private void enterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterKeyPressed
        if(evt.getExtendedKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            submitBtn.doClick();
        arrayNameTxtField.requestFocusInWindow();
    }//GEN-LAST:event_enterKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrayNameLbl;
    private javax.swing.JTextField arrayNameTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton fivHunElementsRadioBtn;
    private javax.swing.JRadioButton hunElementsRadioBtn;
    private javax.swing.ButtonGroup numElementBtnGroup;
    private javax.swing.JLabel numElementsLbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton tenElementsRadioBtn;
    // End of variables declaration//GEN-END:variables
}
